IrisPe17/rent-a-chef

app/models/booking.rb
=> added validations to booking model

Gemfile.lock, app/models/chef.rb, app/models/review.rb
Added presence validations for Chef and Review models.
=> Added validations for Chef and Review models.

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/views/pages/styleguide.html.erb
added html in the styleguide page and css with new color and shape
=> Footer ready, both the html and the css

app/controllers/chefs_controller.rb, app/views/chefs/new.html.erb
Created New View for Chefs controllers. @IrisPe17 please review
=> Created New view for chefs controller.

app/views/chefs/index.html.erb
created a view page for listing all chefs, a basic card created, will be updated after having the card component
@cvillen please review
=> basic ndex view for chefs created

app/controllers/chefs_controller.rb
=> bug fixed on create method.

app/views/chefs/show.html.erb
Added show view. Please @IrisPe17 review :)
=> Created show view.

app/views/chefs/index.html.erb
Added links to to Create new chef and Show by clicking on the Chef's name in the Index view. @IrisPe17 please review
=> Added links to Create and Show in the Index view.

config/environments/development.rb, config/environments/production.rb, config/storage.yml, db/migrate/20210608142939_create_active_storage_tables.active_storage.rb, db/schema.rb
Configured active storage and cloudinary settings on development and production files
@cvillen please take a look
=> Active storage

app/views/chefs/index.html.erb
Removed raise keyword from the chef's cards in index view. @IrisPe17 please review.
=> Amended text showing in cards in index view.

app/controllers/chefs_controller.rb, app/models/chef.rb
allowed photo upload,
added has_one attached photo to a chef model, and permited it in chefs controller
@cvillen, please review
=> Image upload

app/assets/stylesheets/components/_button.scss, app/views/chefs/index.html.erb, app/views/chefs/new.html.erb, app/views/chefs/show.html.erb
Added buttons components in index, show and create views.
=> Implemented css buttons.

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/banner-orange.scss, app/views/pages/styleguide.html.erb
Created the top orange banner (burger). Looking good
=> Create first iteration of the chef card + the top orange banner

Gemfile
=> removed dotenv gem that was allready in gemfile

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/banner-orange.scss, app/views/chefs/index.html.erb, app/views/chefs/new.html.erb, app/views/chefs/show.html.erb, app/views/layouts/application.html.erb, app/views/pages/styleguide.html.erb, app/views/shared/_banner.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_navbar.html.erb
all elements added to the relevant pages 
+ navbar with some links working (crating a new chef and homepage)
=> footer,navbar and banner added to all relevant pages 

.gitignore, Gemfile, Gemfile.lock, app/controllers/chefs_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/init_mapbox.js, app/models/chef.rb, app/views/chefs/index.html.erb, app/views/layouts/application.html.erb, config/initializers/geocoder.rb, db/migrate/20210609095945_add_coordinates_to_chefs.rb, db/schema.rb, package.json, yarn.lock
Added gem 'geocoder', columns 'latitude' and 'longitude' in model, controller, markers. 
Fitted map to markers.
=> Added map and markers.

app/controllers/chefs_controller.rb
Fixed a bug in the index action for the map.
=> Fixed the index action in the controller.

app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_show.scss, app/views/chefs/show.html.erb, app/views/pages/home.html.erb
Styled the chef profile view
The photo should be added after finishing with cloudinary configuration.
Also tomorrow we should add the map and the tags (categories)
=> styled the chef profile view, photo is missing

app/controllers/chefs_controller.rb
authentication fix
@cvillen please check it
=> authentication fix

app/assets/stylesheets/pages/_show.scss, app/views/chefs/show.html.erb
=> added photo to a show pages

app/views/chefs/index.html.erb, app/views/chefs/show.html.erb, db/seeds.rb
=> Cards grid

app/assets/stylesheets/components/_cards.scss, app/views/chefs/index.html.erb, app/views/chefs/show.html.erb
=> conditions for photo and avatar attachment added

app/javascript/plugins/init_mapbox.js, app/views/layouts/application.html.erb
-moved fit markers line to fit inside a map, in initMapbox function
- removed font awesome from application.html.erb head
- @cvillen, @silsc, @flaviadteixeira 
@cvillen  please review
=> moved marker line, removed font awesome

app/assets/stylesheets/components/_cards.scss, app/views/chefs/show.html.erb, db/seeds.rb
+ changed the pics to meals
+ added avatars to the seeds
+ resized the avatars
+ added consistent box shadowing
=> changed the chef cards back to meals + seeds

app/assets/stylesheets/components/_button.scss, app/views/devise/registrations/new.html.erb
Added css to the sign up form.
=> Sign up form

app/views/devise/sessions/new.html.erb
=> Sign in form

app/views/devise/registrations/new.html.erb
=> Changed button color.

app/views/devise/passwords/new.html.erb
=> Add devise into the container.

Gemfile, Gemfile.lock, app/controllers/chefs_controller.rb, app/controllers/pages_controller.rb, app/models/chef.rb, app/views/pages/featured.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb
Added the featured view, a new gem and created the search function
=> added the featured view and the search function

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/views/chefs/index.html.erb
Removed food category from index page,
made cards clickable - link to show page,
added some styling,
reposisioned map
@silsc please check it
=> Index clickable cards

app/assets/stylesheets/pages/_show.scss, app/controllers/application_controller.rb, app/controllers/bookings_controller.rb, app/controllers/chefs_controller.rb, app/controllers/dashboards_controller.rb, app/controllers/pages_controller.rb, app/views/bookings/index.html.erb, app/views/bookings/new.html.erb, app/views/bookings/show.html.erb, app/views/chefs/show.html.erb, app/views/dashboards/show.html.erb, app/views/pages/featured.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb, test/controllers/bookings_controller_test.rb, test/controllers/dashboards_controller_test.rb
=> added and styled the booking and the link in the navbar

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_index.scss, app/views/bookings/index.html.erb, app/views/bookings/new.html.erb, app/views/chefs/index.html.erb, app/views/chefs/new.html.erb, app/views/chefs/show.html.erb, app/views/pages/featured.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
Some minor changes in other views.
=> Mayor style changes in featured and index views

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_reviews.scss, app/views/chefs/show.html.erb, db/seeds.rb
++ added reviews to the chef show page
-- missing the average rating
-- need some refinement with the other elements of the page
=> added reviews to the chef show page

app/views/bookings/show.html.erb
styled the booking confirmation view
=> styled the booking confirmation view

app/views/shared/_navbar.html.erb
=> fixed log out

app/views/dashboards/show.html.erb
Conditional for booking dashboard added
@silsc please review
=> added conditional statement

app/assets/stylesheets/components/_button.scss, app/views/bookings/show.html.erb, app/views/chefs/show.html.erb
changed style for secondary buttons and changed the path for the booking confirmation button
=> changed style for secondary buttons

app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb
Changed width, height and background color of the cards.
=> Instruction cards

app/views/chefs/index.html.erb
added a message for not showing any chef in the search
need to style it (there's some problems with the grid system)
=> added a message

app/views/chefs/index.html.erb, app/views/pages/featured.html.erb
category tags changed for chefs
@silsc
=> tag changed

db/seeds.rb
updated seed information to match the categories and pictures
=> updated seeds information

app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb
added images and css to the instructions cards in the home page.
=> Home cards images

app/assets/stylesheets/pages/_home.scss
Change hover-over color on the cards to match style.
=> Added opacity color to match web page style.

app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb
=> description hover fixed

app/controllers/chefs_controller.rb, app/views/dashboards/show.html.erb
=> total price included

app/controllers/application_controller.rb
=> redirect to featured after sign up
